### PR TITLE
Add JS/TS configuration

### PR DESCRIPTION
**Pull request by lucas-paulger-sonarsource**
Ismail and I ran into some configuration needs when setting up IntelliJ to run the web project.

### CODE REVIEW

**Review by ismailcherri — APPROVED** [review]
LGTM ✨

**Comment by lucas-paulger-sonarsource** [comment]
> There's actually a solution for Prettier that doesn't require a plugin and it is what I am using. Did you consider it? I am trying the plugin now to see how it compares

Let me know what you think, I did not try the non-plugin route.

**Comment by ismailcherri** [comment]
> There's actually a solution for Prettier that doesn't require a plugin and it is what I am using. Did you consider it? I am trying the plugin now to see how it compares

I prefer the plugin approach because it is easier to setup

**Comment by gregaubert** [comment]
Looks good from my point of view! It might be worth pinging SQ, SonarLint or JS/TS bubble to know if any of them are also using IntelliJ and get their opinion on the config

**Pull request merged**
