### PR TITLE
BUILD-2029 fold blank lines at 140 in java

### PR DESCRIPTION
**Pull request by nicolas-gouteux-sonarsource**

### CODE REVIEW

**Comment by nicolas-gouteux-sonarsource** [comment]
Hmm. Not sure to agree when you say:
"compared to people who have already set-up their formatting"
Not sure that formatting is a personal choice right?
:-)

Also, having a margin at 140 without folding seems to make little sense right?

**Comment by nicolas-gouteux-sonarsource** [comment]
But I agree we can do a discuss for sure

**Comment by tom-vanbraband-sonarsource** [comment]
> Hmm. Not sure to agree when you say: "compared to people who have already set-up their formatting" Not sure that formatting is a personal choice right? :-)
> 
> Also, having a margin at 140 without folding seems to make little sense right?

No, it's not a personal choice. But any update we make to these guidelines will not magically appear in SonarSourcers formatting settings. Only new-joiners will go through this set-up and apply the changes, that's why there would be a discrepancy. 

Standards are indeed not a personal choice, but we should leave room for other peoples input as this repository gets used by the whole company

**Comment by nicolas-gouteux-sonarsource** [comment]
Absolutely , you are right. We are making changes to a shared resource. I am not sure of

1) who has authority to change?
2) how does one advertise of changes?

**Comment by tom-vanbraband-sonarsource** [comment]
> 1. who has authority to change?
Everyone, provided the decision making model is followed: https://xtranet-sonarsource.atlassian.net/wiki/spaces/ADM/pages/541919/Decision-Making+Model
> 2. how does one advertise of changes?
That's a tricky one, for sure creating a discuss post explaining why and inviting feedback is necessary. On top of that we could send an e-mail to all developers at SonarSource highlighting the post, but this would be quite noisy for such a small change. The communication guidelines are not super clear on that one: https://xtranet-sonarsource.atlassian.net/wiki/spaces/ADM/pages/206700706/Communication

**Comment by nicolas-gouteux-sonarsource** [comment]
Created https://discuss.sonarsource.com/t/developer-toolset-for-sonar-projects/11980

**Comment by julien-carsique-sonarsource** [comment]
Please create a BUILD ticket to reference in the commit title and describe the change.

**Comment by julien-carsique-sonarsource** [comment]
In the IDE, the option is named "Ensure right margin is not exceeded".
LGTM

**Review by julien-carsique-sonarsource — APPROVED** [review]

**Pull request merged**
