### PR TITLE
Removing spush command from toolset docs

### PR DESCRIPTION
**Pull request by belen-pruvost-sonarsource**
**Description:** Removing `spush` command from the toolset `README` file, based on [the survey](https://sonarsource.slack.com/archives/CJ8L44WRF/p1603990141360700) we ran it has been retired.

### CODE REVIEW

**Comment by julienlancelot** [comment]
The spush script itself should also be removed : https://github.com/SonarSource/sonar-developer-toolset/blob/docs/spush-removal/git/spush

**Review by pierre-guillot-sonarsource — APPROVED** [review]

**Comment by belen-pruvost-sonarsource** [comment]
> /polls "Keep it" "Remove it"

@malena-ebert-sonarsource 🥁 Suspense time!

**Comment by malena-ebert-sonarsource** [comment]
> > /polls "Keep it" "Remove it"
> 
> @malena-ebert-sonarsource drum Suspense time!

@belen-pruvost-sonarsource This GH App only works on issues :/

**Pull request merged**
